# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-12 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preresulttasks_techinforch_techinforde_techinforen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Mode_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='end_time',
        ),
    ]
