# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180112_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
