# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180213_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techinforen',
            old_name='MidtermDuration',
            new_name='MidDuration',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mode_id',
            field=models.CharField(default='', max_length=5, verbose_name='\u6a21\u8fd0\u7b97\u7ed3\u679c'),
        ),
    ]
