from django.conf.urls import url,include
from django.views.generic import View

from .views import LoginChView,LoginEnView,LoginDeView
from . import views

urlpatterns = [
        url('^$', views.home),
        url('^2$', views.PreAddA ),
        url('^1$', views.CH_Top2),
        url('^3$', views.ajax_test_add,name='Ajaxadd'),
        url('^4$', views.home4),

        url('^CH/overview$', views.Chlink,name='Chlink'),
        url('^CH/instro$', views.Chintro,name='Chinstro'),
        url('^CH/log$', views.LogCh, name='LogCh'),
        url('^CH/pre$', LoginChView.as_view(), name='LoginCh'),
        url('^CH/pre1$', views.PreAdd, name='PreAdd'),
        url('^CH/preA$', views.PreAddA, name='PreAddA'),
        url('^CH/preB$', views.PreAddB, name='PreAddB'),
        url('^CH/pre2$', views.PreAdd1, name='ChPreAdd1'),
        url('^CH/intro$', views.PreAdd2, name='ChPreAdd2'),
        url('^CH/ch$', views.SwitchCH, name='SwitchCH'),
        url('^CH/post3$', views.AddPost3, name='Addpost3'),
        url('^CH/post3A$', views.AddPost31, name='Addpost3A'),
        url('^CH/post3B$', views.AddPost32, name='Addpost3B'),


        url('^CH/B/add1$', views.B_AddTech1, name='B_Addtech1'),
        url('^CH/testblank$', views.Checkblank, name='Checkblank'),
        url('^CH/checkblank$', views.CHIntroblank, name='Chintroblank'),
        url('^CH/B/post1A$', views.B_AddPost1A, name='B_Addpost1A'),
        url('^CH/B/post1B$', views.B_AddPost1B, name='B_Addpost1B'),
        url('^CH/B/2$', views.CH_blank2, name='B_2'),
        url('^CH/B/add2$', views.B_AddTech2, name='B_Addtech2'),
        url('^CH/B/post2A$', views.B_AddPost2A, name='B_Addpost2A'),
        url('^CH/B/post2B$', views.B_AddPost2B, name='B_Addpost2B'),
        url('^CH/B/3$', views.CH_blank3, name='B_3'),
        url('^CH/B/add3$', views.B_AddTech3, name='B_Addtech3'),

        url('^CH/T/add1$', views.T_AddTech1, name='T_Addtech1'),
        url('^CH/testtop$', views.CHIntrotop, name='Chintrotop'),
        url('^CH/checkbtop$', views.Checktop, name='Checktop'),
        url('^CH/T/post1A$', views.T_AddPost1A, name='T_Addpost1A'),
        url('^CH/T/post1B$', views.T_AddPost2B, name='T_Addpost1B'),
        url('^CH/T/2$', views.CH_Top2, name='T_2'),
        url('^CH/T/add2$', views.T_AddTech2, name='T_Addtech2'),
        url('^CH/T/post2A$', views.T_AddPost2A, name='T_Addpost2A'),
        url('^CH/T/post2B$', views.T_AddPost2B, name='T_Addpost2B'),
        url('^CH/T/3$', views.CH_Top3, name='T_3'),
        url('^CH/T/add3$', views.T_AddTech3, name='T_Addtech3'),

        url('^CH/U/add1$', views.U_AddTech1, name='U_Addtech1'),
        url('^CH/testup$', views.CHIntroup, name='Chintroup'),
        url('^CH/checkup$', views.Checkup, name='Checkup'),
        url('^CH/U/post1A$', views.U_AddPost1A, name='U_Addpost1A'),
        url('^CH/U/post1A$', views.U_AddPost1B, name='U_Addpost1B'),
        url('^CH/U/2$', views.CH_Up2, name='U_2'),
        url('^CH/U/add2$', views.U_AddTech2, name='U_Addtech2'),
        url('^CH/U/post2A$', views.U_AddPost2A, name='U_Addpost2A'),
        url('^CH/U/post2B$', views.U_AddPost2B, name='U_Addpost2B'),
        url('^CH/U/3$', views.CH_Up3, name='U_3'),
        url('^CH/U/add3$', views.T_AddTech3, name='U_Addtech3'),

        url('^CH/C/add1$', views.C_AddTech1, name='C_Addtech1'),
        url('^CH/testtag$', views.CHIntrotag, name='Chintrotag'),
        url('^CH/checkbtag$', views.Checktag, name='Checktag'),
        url('^CH/C/post1A$', views.C_AddPost1A, name='C_Addpost1A'),
        url('^CH/C/post1B$', views.C_AddPost1B, name='C_Addpost1B'),
        url('^CH/C/2$', views.CH_C2, name='C_2'),
        url('^CH/C/add2$', views.C_AddTech2, name='C_Addtech2'),
        url('^CH/C/post2A$', views.C_AddPost2A, name='C_Addpost2A'),
        url('^CH/C/post2B$', views.C_AddPost2B, name='C_Addpost2B'),
        url('^CH/C/3$', views.CH_C3, name='C_3'),
        url('^CH/C/add3$', views.C_AddTech3, name='C_Addtech3'),



        url('^EN/overview$', views.Enlink, name='Enlink'),
        url('^EN/instro$', views.Eninstro, name='Eninstro'),
        url('^EN/log$', views.LogEn, name='LogEn'),
        url('^EN/pre$', LoginEnView.as_view() , name='LoginEn'),
        url('^EN/add$', views.PreAddEn, name='PreAddEn'),
        url('^EN/preA$', views.PreAddEnA, name='PreAddEnA'),
        url('^EN/preB$', views.PreAddEnB, name='PreAddEnB'),
        url('^EN/pre1$', views.PreAddEn1, name='PreAddEn1'),
        url('^EN/intro$', views.PreAddEn2, name='PreAddEn2'),
        url('^EN/ch$', views.SwitchEN, name='SwitchEN'),
        url('^EN/post3A$', views.AddPost3AEn, name='AddPost3AEn'),
        url('^EN/post3B$', views.AddPost3BEn, name='AddPost3BEn'),
        url('^EN/post3C$', views.AddPost3CEn, name='AddPost3CEn'),

        url('^EN/B/add1$', views.B_AddTech1EN, name='B_Addtech1EN'),
        url('^EN/testblank$', views.ENIntroblank, name='ENintroblank'),
        url('^EN/checkblank$', views.ENCheckblank, name='ENCheckblank'),
        url('^EN/B/post1A$', views.B_AddPost1AEN, name='B_Addpost1AEN'),
        url('^EN/B/post1B$', views.B_AddPost1BEN, name='B_Addpost1BEN'),
        url('^EN/B/2$', views.EN_blank2, name='EnB_2'),
        url('^EN/B/add2$', views.B_AddTech2EN, name='B_Addtech2EN'),
        url('^EN/B/post2A$', views.B_AddPost2AEN, name='B_Addpost2AEN'),
        url('^EN/B/post2B$', views.B_AddPost2BEN, name='B_Addpost2BEN'),
        url('^EN/B/3$', views.EN_blank3, name='EnB_3'),
        url('^EN/B/add3$', views.B_AddTech3EN, name='B_Addtech3EN'),


        url('^EN/T/add1$', views.T_AddTech1EN, name='T_Addtech1EN'),
        url('^EN/testtop$', views.ENIntrotop, name='ENintrotop'),
        url('^EN/checktop$', views.ENChecktop, name='ENChecktop'),
        url('^EN/T/post1A$', views.T_AddPost1AEN, name='T_Addpost1AEN'),
        url('^EN/T/post1B$', views.T_AddPost1BEN, name='T_Addpost1BEN'),
        url('^EN/T/2$', views.EN_Top2, name='EnT_2'),
        url('^EN/T/add2$', views.T_AddTech2EN, name='T_Addtech2EN'),
        url('^EN/T/post2A$', views.T_AddPost2AEN, name='T_Addpost2AEN'),
        url('^EN/T/post2B$', views.T_AddPost2BEN, name='T_Addpost2BEN'),
        url('^EN/T/3$', views.EN_Top3, name='EnT_3'),
        url('^EN/T/add3$', views.T_AddTech3EN, name='T_Addtech3EN'),


        url('^EN/U/add1$', views.U_AddTech1EN, name='U_Addtech1EN'),
        url('^EN/testup$', views.ENIntroup, name='ENintroup'),
        url('^EN/checkup$', views.ENCheckup, name='ENCheckup'),
        url('^EN/U/post1A$', views.U_AddPost1AEN, name='U_Addpost1AEN'),
        url('^EN/U/post1B$', views.U_AddPost1BEN, name='U_Addpost1BEN'),
        url('^EN/U/2$', views.EN_Up2, name='EnU_2'),
        url('^EN/U/add2$', views.U_AddTech2EN, name='U_Addtech2EN'),
        url('^EN/U/post2A$', views.U_AddPost2AEN, name='U_Addpost2AEN'),
        url('^EN/U/post2B$', views.U_AddPost2BEN, name='U_Addpost2BEN'),
        url('^EN/U/3$', views.EN_Up3, name='EnU_3'),
        url('^EN/U/add3$', views.T_AddTech3EN, name='U_Addtech3EN'),


        url('^EN/C/add1$', views.C_AddTech1EN, name='C_Addtech1EN'),
        url('^EN/testtag$', views.ENIntrotag, name='ENintrotag'),
        url('^EN/checktag$', views.ENChecktag, name='ENChecktag'),
        url('^EN/C/post1A$', views.C_AddPost1AEN, name='C_Addpost1AEN'),
        url('^EN/C/post1B$', views.C_AddPost1BEN, name='C_Addpost1BEN'),
        url('^EN/C/2$', views.EN_C2, name='EnC_2'),
        url('^EN/C/add2$', views.C_AddTech2EN, name='C_Addtech2EN'),
        url('^EN/C/post2A$', views.C_AddPost2AEN, name='C_Addpost2AEN'),
        url('^EN/C/post2B$', views.C_AddPost2BEN, name='C_Addpost2BEN'),
        url('^EN/C/3$', views.EN_C3, name='EnC_3'),
        url('^EN/C/add3$', views.C_AddTech3EN, name='C_Addtech3EN'),



        url('^DE/overview$', views.Delink, name='Delink'),
        url('^DE/instro$', views.Deinstro, name='Deinstro'),
        url('^DE/log$', views.LogDe, name='LogDe'),
        url('^DE/pre$', LoginDeView.as_view(), name='LoginDe'),
        url('^DE/add$', views.PreAddDe, name='PreAddDe'),
        url('^DE/preA$', views.PreAddDeA, name='PreAddDeA'),
        url('^DE/preB$', views.PreAddDeB, name='PreAddDeB'),
        url('^DE/pre1$', views.PreAddDe1, name='PreAddDe1'),
        url('^DE/intro$', views.PreAddDe2, name='PreAddDe2'),
        url('^DE/t1$', views.DeTask1, name='DeTask1'),
        url('^DE/ch$', views.SwitchDE, name='SwitchDE'),

        url('^DE/B/add1$', views.B_AddTech1DE, name='B_Addtech1De'),
        url('^DE/testblank$', views.DEIntroblank, name='DEintroblank'),
        url('^DE/checkblank$', views.DECheckblank, name='DECheckblank'),
        url('^DE/B/post1$', views.B_AddPost1DE, name='B_Addpost1De'),
        url('^DE/B/2$', views.DE_blank2, name='B_2DE'),
        url('^DE/B/add2$', views.B_AddTech2DE, name='B_Addtech2DE'),
        url('^DE/B/post2$', views.B_AddPost2DE, name='B_Addpost2DE'),
        url('^DE/B/3$', views.DE_blank3, name='B_3DE'),
        url('^DE/B/add3$', views.B_AddTech3DE, name='B_Addtech3DE'),
        url('^DE/B/post3$', views.AddPost3, name='Addpost3'),

        url('^DE/T/add1$', views.T_AddTech1DE, name='T_Addtech1DE'),
        url('^DE/testtop$', views.DEIntrotop, name='DEintrotop'),
        url('^DE/checktop$', views.DEChecktop, name='DEChecktop'),
        url('^DE/T/post1$', views.T_AddPost1DE, name='T_Addpost1DE'),
        url('^DE/T/2$', views.DE_Top2, name='T_2DE'),
        url('^DE/T/add2$', views.T_AddTech2DE, name='T_Addtech2DE'),
        url('^DE/T/post2$', views.T_AddPost2DE, name='T_Addpost2DE'),
        url('^DE/T/3$', views.DE_Top3, name='T_3DE'),
        url('^DE/T/add3$', views.T_AddTech3DE, name='T_Addtech3DE'),
        url('^DE/T/post3$', views.AddPost3De, name='Addpost3DE'),
        url('^DE/T/post3A$', views.AddPost3ADe, name='Addpost3ADE'),
        url('^DE/T/post3B$', views.AddPost3BDe, name='Addpost3BDE'),

        url('^DE/U/add1$', views.U_AddTech1DE, name='U_Addtech1DE'),
        url('^DE/testup$', views.DEIntroup, name='DEintroup'),
        url('^DE/checkup$', views.DECheckup, name='DECheckup'),
        url('^DE/U/post1$', views.U_AddPost1DE, name='U_Addpost1DE'),
        url('^DE/U/2$', views.DE_Up2, name='U_2DE'),
        url('^DE/U/add2$', views.U_AddTech2DE, name='U_Addtech2DE'),
        url('^DE/U/post2$', views.U_AddPost2DE, name='U_Addpost2DE'),
        url('^DE/U/3$', views.DE_Up3, name='U_3DE'),
        url('^DE/U/add3$', views.T_AddTech3DE, name='U_Addtech3DE'),
        url('^DE/U/post3$', views.AddPost3De, name='Addpost3DE'),

        url('^DE/C/add1$', views.C_AddTech1DE, name='C_Addtech1DE'),
        url('^DE/testtag$', views.DEIntrotag, name='DEintrotag'),
        url('^DE/checktag$', views.DEChecktag, name='DEChecktag'),
        url('^DE/C/post1$', views.C_AddPost1DE, name='C_Addpost1DE'),
        url('^DE/C/2$', views.DE_C2, name='C_2DE'),
        url('^DE/C/add2$', views.C_AddTech2DE, name='C_Addtech2DE'),
        url('^DE/C/post2$', views.C_AddPost2DE, name='C_Addpost2DE'),
        url('^DE/C/3$', views.DE_C3, name='C_3DE'),
        url('^DE/C/add3$', views.C_AddTech3DE, name='C_Addtech3DE'),
        url('^DE/post3$', views.AddPost3De, name='Addpost3DE'),
        url('^DE/post3A$', views.AddPost3ADe, name='Addpost3ADE'),
        url('^DE/post3B$', views.AddPost3BDe, name='Addpost3BDE'),
        ]