# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuestionResultCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_proficiency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u7cbe\u901a\u7a0b\u5ea6')),
                ('Q2_globalapproach', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u5168\u5c40')),
                ('Q3_localizedapproach', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q4_objects', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q5_rulesbased', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q6_learncategory', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q7_organize', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q8_formallogic', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q9_logicalrules', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q10_individual', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q11_surrounding', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q12_littelrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q13_difficultrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q14_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q15_dialectical', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q16_contradiction', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q17_pressures', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q18_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': 'Post\u95ee\u5377\u7ed3\u679cOne',
                'verbose_name_plural': 'Post\u95ee\u5377\u7ed3\u679cOne',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionResultThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_proficiency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u7cbe\u901a\u7a0b\u5ea6')),
                ('Q2_globalapproach', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u5168\u5c40')),
                ('Q3_localizedapproach', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q4_objects', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q5_rulesbased', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q6_learncategory', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q7_organize', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q8_formallogic', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q9_logicalrules', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q10_individual', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q11_surrounding', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q12_littelrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q13_difficultrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q14_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q15_dialectical', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q16_contradiction', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q17_pressures', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q18_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q19_littelrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q20_difficultrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q21_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q22_dialectical', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q23_contradiction', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q24_pressures', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q25_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': 'Post\u95ee\u5377\u7ed3\u679cThree',
                'verbose_name_plural': 'Post\u95ee\u5377\u7ed3\u679cThree',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionResultTwoCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_proficiency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u7cbe\u901a\u7a0b\u5ea6')),
                ('Q2_globalapproach', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u5168\u5c40')),
                ('Q3_localizedapproach', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q4_objects', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q5_rulesbased', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q6_learncategory', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q7_organize', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q8_formallogic', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q9_logicalrules', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q10_individual', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q11_surrounding', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q12_littelrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q13_difficultrule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q14_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q15_dialectical', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q16_contradiction', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q17_pressures', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q18_thematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': 'Post\u95ee\u5377\u7ed3\u679cTwo',
                'verbose_name_plural': 'Post\u95ee\u5377\u7ed3\u679cTwo',
            },
        ),
        migrations.CreateModel(
            name='PreQuestionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_age', models.CharField(choices=[('<20', '<20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('>51', '>51')], max_length=20, verbose_name='\u5e74\u9f84')),
                ('Q2_gender', models.CharField(choices=[('female', '\u5973'), ('male', '\u7537'), ('other', '\u5176\u4ed6')], max_length=10, verbose_name='\u6027\u522b')),
                ('Q3_nationa', models.CharField(default='', max_length=20, verbose_name='\u56fd\u7c4d')),
                ('Q4_educationlevel', models.CharField(choices=[('UG', 'Undergraduate'), ('Bachelor', "Bachelor's degree"), ('MS', 'Postgraduate (Master)'), ('Master', "Master's degree"), ('DS', 'Doctoral student'), ('Doctorate', 'Doctorate degree')], max_length=20, verbose_name='\u6559\u80b2\u7a0b\u5ea6')),
                ('Q41_educationlevel', models.CharField(default='', max_length=20, verbose_name='\u5176\u4ed6\u6559\u80b2\u7a0b\u5ea6')),
                ('Q5_expertise', multiselectfield.db.fields.MultiSelectField(choices=[('CP', 'Computer program'), ('DS', 'Design service'), ('MA', 'Management'), ('TS', 'Technical service'), ('SR', 'Scientific research'), ('EDU', 'Education')], max_length=50, verbose_name='\u8bbe\u8ba1\u7ecf\u9a8c')),
                ('Q51_expertise', models.CharField(default='', max_length=20, verbose_name='\u5176\u4ed6\u4e13\u4e1a\u77e5\u8bc6')),
                ('Q6_role', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Manager'), ('S', 'Student'), ('D', 'Designer'), ('C', 'Consultant'), ('R', 'Researcher'), ('P', 'Programmer')], max_length=50, verbose_name='\u8bbe\u8ba1\u89d2\u8272')),
                ('Q61_role', models.CharField(default='', max_length=20, verbose_name='\u5176\u4ed6\u89d2\u8272')),
                ('Q7_fulltime', models.CharField(default='', max_length=20, verbose_name='\u5de5\u4f5c\u65f6\u957f')),
                ('Q8_ProjectCount', models.CharField(choices=[(1, '0\u4e2a'), (2, '<3\u4e2a'), (3, '3-5\u4e2a'), (4, '6-10\u4e2a'), (5, '11-15\u4e2a'), (6, '>15\u4e2a')], max_length=10, verbose_name='\u8bbe\u8ba1\u9879\u76ee\u4e2a\u6570')),
                ('Q9_DesigCourse', models.CharField(choices=[(1, '\u6709\u53c2\u52a0\u8fc7'), (2, '\u6ca1\u53c2\u52a0\u8fc7')], max_length=10, verbose_name='\u662f\u5426\u53c2\u52a0\u8fc7\u8bbe\u8ba1\u8bfe\u7a0b\u6216\u8bb2\u5ea7')),
                ('Q10_UsedTechnique', models.CharField(choices=[(1, '\u4f7f\u7528\u8fc7'), (2, '\u6ca1\u4f7f\u7528\u8fc7')], max_length=10, verbose_name='\u662f\u5426\u4f7f\u7528\u8fc7\u8bbe\u8ba1\u6280\u672f')),
                ('Q11_FamiliarTechnique', multiselectfield.db.fields.MultiSelectField(choices=[(1, '\u89d2\u8272\u6a21\u578b'), (2, '\u573a\u666f'), (3, '\u51fa\u58f0\u601d\u8003'), (4, '\u5361\u8bfa\u5206\u6790'), (5, '\u89d2\u8272\u626e\u6f14'), (6, '\u884c\u4e3a\u5730\u56fe'), (7, '\u4ee5\u4e0a\u90fd\u4e0d\u662f')], max_length=50, verbose_name='\u719f\u6089\u7684\u6280\u672f')),
                ('Q12_knewpretty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u7cbe\u901a\u7a0b\u5ea6')),
                ('Q13_experts', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='\u5168\u5c40')),
                ('Q14_knewless', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q15_donotknow', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q16_donotfeel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q17_lotofexperiences', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q18_familiar', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q19_focusobjects', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q20_basedcategories', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q21_easylearncategories', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q22_organizefunctionally', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q23_useformallogic', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q24_adherelogicalrules', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q25_individualbehavior', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q26_focussurobj', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q27_focussurfeld', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q28_difflearncate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q29_organthematically', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q30_diareasoning', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q31_preflogic', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Q32_peopbehav', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': 'Pre\u95ee\u5377\u7ed3\u679c',
                'verbose_name_plural': 'Pre\u95ee\u5377\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='SelectedTechniqueOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chose_Tech1', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f1')),
                ('chose_Tech2', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f2')),
                ('chose_Tech3', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f3')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u573a\u666fOne\u9009\u62e9\u7684\u7ed3\u679c',
                'verbose_name_plural': '\u573a\u666fOne\u9009\u62e9\u7684\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='SelectedTechniqueThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chose_Tech1', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f1')),
                ('chose_Tech2', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f2')),
                ('chose_Tech3', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f3')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u573a\u666fThree\u7684\u9009\u62e9\u7ed3\u679c',
                'verbose_name_plural': '\u573a\u666fThree\u7684\u9009\u62e9\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='SelectedTechniqueTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chose_Tech1', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f1')),
                ('chose_Tech2', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f2')),
                ('chose_Tech3', models.TextField(default='', max_length=200, verbose_name='\u9009\u62e9\u7684\u6280\u672f3')),
                ('Test_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u573a\u666fTwo\u7684\u9009\u62e9\u7ed3\u679c',
                'verbose_name_plural': '\u573a\u666fTwo\u7684\u9009\u62e9\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('female', '\u5973'), ('male', '\u7537'), ('other', '\u5176\u4ed6')], max_length=10, verbose_name='\u6027\u522b')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5',
                'verbose_name_plural': '\u6d4b\u8bd5',
            },
        ),
    ]
