# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostQuestionResultCH',
            new_name='PostQuestionResultOne',
        ),
    ]
