# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0002_auto_20180107_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostQuestionResultTwoCH',
            new_name='PostQuestionResultTwo',
        ),
    ]
