# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0003_auto_20180107_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q10_individual',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q11_surrounding',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q12_littelrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q13_difficultrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q14_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q15_dialectical',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q16_contradiction',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q17_pressures',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q18_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q1_proficiency',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u7cbe\u901a\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q2_globalapproach',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u5168\u5c40'),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q3_localizedapproach',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q4_objects',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q5_rulesbased',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q6_learncategory',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q7_organize',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q8_formallogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultone',
            name='Q9_logicalrules',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q10_individual',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q11_surrounding',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q12_littelrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q13_difficultrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q14_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q15_dialectical',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q16_contradiction',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q17_pressures',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q18_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q19_littelrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q1_proficiency',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u7cbe\u901a\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q20_difficultrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q21_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q22_dialectical',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q23_contradiction',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q24_pressures',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q25_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q2_globalapproach',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u5168\u5c40'),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q3_localizedapproach',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q4_objects',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q5_rulesbased',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q6_learncategory',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q7_organize',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q8_formallogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresultthree',
            name='Q9_logicalrules',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q10_individual',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q11_surrounding',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q12_littelrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q13_difficultrule',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q14_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q15_dialectical',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q16_contradiction',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q17_pressures',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q18_thematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q1_proficiency',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u7cbe\u901a\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q2_globalapproach',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u5168\u5c40'),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q3_localizedapproach',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q4_objects',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q5_rulesbased',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q6_learncategory',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q7_organize',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q8_formallogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='postquestionresulttwo',
            name='Q9_logicalrules',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q10_UsedTechnique',
            field=models.CharField(choices=[(1, '\u4f7f\u7528\u8fc7'), (2, '\u6ca1\u4f7f\u7528\u8fc7')], max_length=10, null=True, verbose_name='\u662f\u5426\u4f7f\u7528\u8fc7\u8bbe\u8ba1\u6280\u672f'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q11_FamiliarTechnique',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '\u89d2\u8272\u6a21\u578b'), (2, '\u573a\u666f'), (3, '\u51fa\u58f0\u601d\u8003'), (4, '\u5361\u8bfa\u5206\u6790'), (5, '\u89d2\u8272\u626e\u6f14'), (6, '\u884c\u4e3a\u5730\u56fe'), (7, '\u4ee5\u4e0a\u90fd\u4e0d\u662f')], max_length=50, null=True, verbose_name='\u719f\u6089\u7684\u6280\u672f'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q12_knewpretty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u7cbe\u901a\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q13_experts',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u5168\u5c40'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q14_knewless',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q15_donotknow',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q16_donotfeel',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q17_lotofexperiences',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q18_familiar',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q19_focusobjects',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q1_age',
            field=models.CharField(choices=[('<20', '<20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('>51', '>51')], max_length=20, null=True, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q20_basedcategories',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q21_easylearncategories',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q22_organizefunctionally',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q23_useformallogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q24_adherelogicalrules',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q25_individualbehavior',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q26_focussurobj',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q27_focussurfeld',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q28_difflearncate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q29_organthematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q2_gender',
            field=models.CharField(choices=[('female', '\u5973'), ('male', '\u7537'), ('other', '\u5176\u4ed6')], max_length=10, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q30_diareasoning',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q31_preflogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q32_peopbehav',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q3_nationa',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='\u56fd\u7c4d'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q41_educationlevel',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='\u5176\u4ed6\u6559\u80b2\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q4_educationlevel',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('Bachelor', "Bachelor's degree"), ('MS', 'Postgraduate (Master)'), ('Master', "Master's degree"), ('DS', 'Doctoral student'), ('Doctorate', 'Doctorate degree')], max_length=20, null=True, verbose_name='\u6559\u80b2\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q51_expertise',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='\u5176\u4ed6\u4e13\u4e1a\u77e5\u8bc6'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q5_expertise',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CP', 'Computer program'), ('DS', 'Design service'), ('MA', 'Management'), ('TS', 'Technical service'), ('SR', 'Scientific research'), ('EDU', 'Education')], max_length=50, null=True, verbose_name='\u8bbe\u8ba1\u7ecf\u9a8c'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q61_role',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='\u5176\u4ed6\u89d2\u8272'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q6_role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Manager'), ('S', 'Student'), ('D', 'Designer'), ('C', 'Consultant'), ('R', 'Researcher'), ('P', 'Programmer')], max_length=50, null=True, verbose_name='\u8bbe\u8ba1\u89d2\u8272'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q7_fulltime',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='\u5de5\u4f5c\u65f6\u957f'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q8_ProjectCount',
            field=models.CharField(choices=[(1, '0\u4e2a'), (2, '<3\u4e2a'), (3, '3-5\u4e2a'), (4, '6-10\u4e2a'), (5, '11-15\u4e2a'), (6, '>15\u4e2a')], max_length=10, null=True, verbose_name='\u8bbe\u8ba1\u9879\u76ee\u4e2a\u6570'),
        ),
        migrations.AlterField(
            model_name='prequestionresult',
            name='Q9_DesigCourse',
            field=models.CharField(choices=[(1, '\u6709\u53c2\u52a0\u8fc7'), (2, '\u6ca1\u53c2\u52a0\u8fc7')], max_length=10, null=True, verbose_name='\u662f\u5426\u53c2\u52a0\u8fc7\u8bbe\u8ba1\u8bfe\u7a0b\u6216\u8bb2\u5ea7'),
        ),
    ]
