# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0004_auto_20180107_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.AddField(
            model_name='postquestionresultone',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
        migrations.AddField(
            model_name='postquestionresultthree',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
        migrations.AddField(
            model_name='postquestionresulttwo',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
        migrations.AddField(
            model_name='selectedtechniqueone',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
        migrations.AddField(
            model_name='selectedtechniquethree',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
        migrations.AddField(
            model_name='selectedtechniquetwo',
            name='mode_id',
            field=models.CharField(default='', max_length=1, verbose_name='\u6a21Id'),
        ),
    ]
