# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-12 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0005_auto_20180111_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquestionresultthree',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
