# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0007_auto_20180203_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prequestionresult1',
            name='Test_User',
        ),
        migrations.RemoveField(
            model_name='prequestionresult2',
            name='Test_User',
        ),
        migrations.RemoveField(
            model_name='postquestionresultone',
            name='Q17_pressures',
        ),
        migrations.RemoveField(
            model_name='postquestionresultone',
            name='Q18_thematically',
        ),
        migrations.RemoveField(
            model_name='postquestionresulttwo',
            name='Q17_pressures',
        ),
        migrations.RemoveField(
            model_name='postquestionresulttwo',
            name='Q18_thematically',
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q12_knewpretty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u7cbe\u901a\u7a0b\u5ea6'),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q13_experts',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='\u5168\u5c40'),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q14_knewless',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q15_donotknow',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q16_donotfeel',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q17_lotofexperiences',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q18_familiar',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q19_focusobjects',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q20_basedcategories',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q21_easylearncategories',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q22_organizefunctionally',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q23_useformallogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q24_adherelogicalrules',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q25_individualbehavior',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q26_focussurobj',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q27_focussurfeld',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q28_difflearncate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q29_organthematically',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q30_diareasoning',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q31_preflogic',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='Q32_peopbehav',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='PreQuestionResult1',
        ),
        migrations.DeleteModel(
            name='PreQuestionResult2',
        ),
    ]
