# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0008_auto_20180204_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='prequestionresult',
            name='CountryName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='CountryYears',
            field=models.IntegerField(null=True, verbose_name='\u5e74\u957f'),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='FC_1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='FC_2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='FC_3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='FC_4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='FC_5',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='FC_6',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prequestionresult',
            name='ForeignCountry',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
