# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0009_auto_20180206_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequestionresult',
            name='ForeignCountry',
            field=models.CharField(choices=[(1, '\u6709\u5728\u56fd\u5916\u751f\u6d3b\u8fc7'), (2, '\u6ca1\u6709\u751f\u6d3b\u8fc7')], default='', max_length=6, null=True),
        ),
    ]
