# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0011_auto_20180206_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequestionresult',
            name='ForeignCountry',
            field=models.CharField(choices=[('Yes', '\u6709\u5728\u56fd\u5916\u751f\u6d3b'), ('No', '\u6ca1\u6709\u751f\u6d3b\u8fc7')], default='', max_length=6, null=True),
        ),
    ]
