# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0012_auto_20180206_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prequestionresult',
            old_name='ForeignCountry',
            new_name='livecountry',
        ),
    ]
