# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0013_auto_20180206_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequestionresult',
            name='livecountry',
            field=models.CharField(choices=[('Yes', '\u662f'), ('No', '\u5426')], default='', max_length=6, null=True),
        ),
    ]
