# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0016_auto_20180209_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequestionresult',
            name='CountryYears',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='\u5e74\u957f'),
        ),
    ]
