# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selected', '0017_auto_20180209_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquestionresultthree',
            name='Q23_contradiction',
        ),
        migrations.RemoveField(
            model_name='postquestionresultthree',
            name='Q24_pressures',
        ),
        migrations.RemoveField(
            model_name='postquestionresultthree',
            name='Q25_thematically',
        ),
    ]
