# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUCollectionCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collection_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587BottomUp\u6536\u96c6\u8bbe\u8ba1\u6570\u636e')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587Bottomup\u6536\u96c6\u8bbe\u8ba1\u6570\u636e',
                'verbose_name_plural': '\u4e2d\u6587Bottomup\u6536\u96c6\u8bbe\u8ba1\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='BUCollectionDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collection_Name', models.CharField(default='', max_length=50, verbose_name='\u5fb7\u8bedBottomUp\u6536\u96c6\u8bbe\u8ba1\u6570\u636e')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedBottomup\u6536\u96c6\u8bbe\u8ba1\u6570\u636e',
                'verbose_name_plural': '\u5fb7\u8bedBottomup\u6536\u96c6\u8bbe\u8ba1\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='BUCollectionEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collection_Name', models.CharField(default='', max_length=30, verbose_name='\u82f1\u6587BottomUp\u6536\u96c6\u8bbe\u8ba1\u6570\u636e')),
            ],
            options={
                'verbose_name': '\u82f1\u6587Bottomup\u6536\u96c6\u8bbe\u8ba1\u6570\u636e',
                'verbose_name_plural': '\u82f1\u6587Bottomup\u6536\u96c6\u8bbe\u8ba1\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='BUDesignCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587BottomUp\u8bbe\u8ba1\u9636\u6bb5')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587Bottomup\u8bbe\u8ba1\u9636\u6bb5',
                'verbose_name_plural': '\u4e2d\u6587Bottomup\u8bbe\u8ba1\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='BUDesignDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedBottomUp\u8bbe\u8ba1\u9636\u6bb5')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedBottomup\u8bbe\u8ba1\u9636\u6bb5',
                'verbose_name_plural': '\u5fb7\u8bedBottomup\u8bbe\u8ba1\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='BUDesignEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587BottomUp\u8bbe\u8ba1\u9636\u6bb5')),
            ],
            options={
                'verbose_name': '\u82f1\u6587Bottomup\u8bbe\u8ba1\u9636\u6bb5',
                'verbose_name_plural': '\u82f1\u6587Bottomup\u8bbe\u8ba1\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='BUDurationCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587Bottomup\u6301\u7eed\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587Bottomup\u6301\u7eed\u65f6\u95f4',
                'verbose_name_plural': '\u4e2d\u6587Bottomup\u6301\u7eed\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='BUDurationDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedBottomup\u6301\u7eed\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedBottomup\u6301\u7eed\u65f6\u95f4',
                'verbose_name_plural': '\u5fb7\u8bedBottomup\u6301\u7eed\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='BUDurationEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587Bottomup\u6301\u7eed\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u82f1\u6587Bottomup\u6301\u7eed\u65f6\u95f4',
                'verbose_name_plural': '\u82f1\u6587Bottomup\u6301\u7eed\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='BUParticipantCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587Bottomup\u53c2\u4e0e\u8005')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587Bottomup\u53c2\u4e0e\u8005',
                'verbose_name_plural': '\u4e2d\u6587Bottomup\u53c2\u4e0e\u8005',
            },
        ),
        migrations.CreateModel(
            name='BUParticipantDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedBottomup\u53c2\u4e0e\u8005')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedBottomup\u53c2\u4e0e\u8005',
                'verbose_name_plural': '\u5fb7\u8bedBottomup\u53c2\u4e0e\u8005',
            },
        ),
        migrations.CreateModel(
            name='BUParticipantEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587Bottomup\u53c2\u4e0e\u8005')),
            ],
            options={
                'verbose_name': '\u82f1\u6587Bottomup\u53c2\u4e0e\u8005',
                'verbose_name_plural': '\u82f1\u6587Bottomup\u53c2\u4e0e\u8005',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostQues_Description', models.TextField(default='', max_length=200, verbose_name='\u4e2d\u6587\u524d\u4e24\u4e2a\u7684Post\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587\u524d\u4e24\u4e2aPost\u95ee\u9898',
                'verbose_name_plural': '\u4e2d\u6587\u524d\u4e24\u4e2aPost\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostQues_Description', models.TextField(default='', max_length=200, verbose_name='\u5fb7\u8bed\u524d\u4e24\u4e2a\u7684Post\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bed\u524d\u4e24\u4e2aPost\u95ee\u9898',
                'verbose_name_plural': '\u5fb7\u8bed\u524d\u4e24\u4e2aPost\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostQues_Description', models.TextField(default='', max_length=200, verbose_name='\u82f1\u6587\u524d\u4e24\u4e2a\u7684Post\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u82f1\u6587\u524d\u4e24\u4e2aPost\u95ee\u9898',
                'verbose_name_plural': '\u82f1\u6587\u524d\u4e24\u4e2aPost\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionPlusCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostQues_Description', models.TextField(default='', max_length=200, verbose_name='\u4e2d\u6587\u6700\u540e\u4e00\u4e2a\u9644\u52a0\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587\u6700\u540e\u4e00\u4e2aPost\u95ee\u9898',
                'verbose_name_plural': '\u4e2d\u6587\u6700\u540e\u4e00\u4e2aPost\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionPlusDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostQues_Description', models.TextField(default='', max_length=200, verbose_name='\u5fb7\u8bed\u6700\u540e\u4e00\u4e2a\u9644\u52a0\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bed\u6700\u540e\u4e00\u4e2aPost\u95ee\u9898',
                'verbose_name_plural': '\u5fb7\u8bed\u6700\u540e\u4e00\u4e2aPost\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PostQuestionPlusEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostQues_Description', models.TextField(default='', max_length=200, verbose_name='\u82f1\u6587\u6700\u540e\u4e00\u4e2a\u9644\u52a0\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u4e2d\u82f1\u6587\u6700\u540e\u4e00\u4e2aPost\u95ee\u9898',
                'verbose_name_plural': '\u4e2d\u82f1\u6587\u6700\u540e\u4e00\u4e2aPost\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='PreQuestionCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreQues_Description', models.TextField(default='', max_length=200, verbose_name='\u4e2d\u6587Pre\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587PreQuestion\u7684\u4fe1\u606f',
                'verbose_name_plural': '\u4e2d\u6587PreQuestion\u7684\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='PreQuestionDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreQues_Description', models.TextField(default='', max_length=200, verbose_name='\u5fb7\u8bedPre\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedPreQuestion\u7684\u4fe1\u606f',
                'verbose_name_plural': '\u5fb7\u8bedPreQuestion\u7684\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='PreQuestionEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreQues_Description', models.TextField(default='', max_length=200, verbose_name='\u82f1\u6587Pre\u95ee\u9898')),
            ],
            options={
                'verbose_name': '\u82f1\u6587PreQuestion\u7684\u4fe1\u606f',
                'verbose_name_plural': '\u82f1\u6587PreQuestion\u7684\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='TagCloudCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagCloud_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587TagCloud\u5206\u7c7b\u540d\u79f0')),
                ('frequency', models.IntegerField(verbose_name='\u9891\u7387')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587TagCloud\u5206\u7c7b\u4fe1\u606f',
                'verbose_name_plural': '\u4e2d\u6587TagCloud\u5206\u7c7b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='TagCloudDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagCloud_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedTagCloud\u5206\u7c7b\u540d\u79f0')),
                ('frequency', models.CharField(default='', max_length=2, verbose_name='\u9891\u7387')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTagCloud\u5206\u7c7b\u4fe1\u606f',
                'verbose_name_plural': '\u5fb7\u8bedTagCloud\u5206\u7c7b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='TagCloudEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagCloud_Name', models.CharField(default='', max_length=50, verbose_name='\u82f1\u6587TagCloud\u5206\u7c7b\u540d\u79f0')),
                ('frequency', models.CharField(default='', max_length=2, verbose_name='\u9891\u7387')),
            ],
            options={
                'verbose_name': '\u82f1\u6587TagCloud\u5206\u7c7b\u4fe1\u606f',
                'verbose_name_plural': '\u82f1\u6587TagCloud\u5206\u7c7b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='TaskDescriptionCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(default='', max_length=1000, verbose_name='\u4e2d\u6587\u573a\u666f\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587Task\u573a\u666f\u63cf\u8ff0',
                'verbose_name_plural': '\u4e2d\u6587Task\u573a\u666f\u63cf\u8ff0',
            },
        ),
        migrations.CreateModel(
            name='TaskDescriptionDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(default='', max_length=1000, verbose_name='\u4e2d\u6587\u573a\u666f\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTask\u573a\u666f\u63cf\u8ff0',
                'verbose_name_plural': '\u5fb7\u8bedTask\u573a\u666f\u63cf\u8ff0',
            },
        ),
        migrations.CreateModel(
            name='TaskDescriptionEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(default='', max_length=1000, verbose_name='\u82f1\u6587\u573a\u666f\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u82f1\u6587Task\u573a\u666f\u63cf\u8ff0',
                'verbose_name_plural': '\u82f1\u6587Task\u573a\u666f\u63cf\u8ff0',
            },
        ),
        migrations.CreateModel(
            name='TDDependencyCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dependency_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587TopDown\u65f6\u95f4\u4f9d\u8d56')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587TopDown\u65f6\u95f4\u4f9d\u8d56\u6027',
                'verbose_name_plural': '\u4e2d\u6587TopDown\u65f6\u95f4\u4f9d\u8d56\u6027',
            },
        ),
        migrations.CreateModel(
            name='TDDependencyDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dependency_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedTopDown\u65f6\u95f4\u4f9d\u8d56')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTopDown\u65f6\u95f4\u4f9d\u8d56\u6027',
                'verbose_name_plural': '\u5fb7\u8bedTopDown\u65f6\u95f4\u4f9d\u8d56\u6027',
            },
        ),
        migrations.CreateModel(
            name='TDDependencyEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dependency_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587TopDown\u65f6\u95f4\u4f9d\u8d56')),
            ],
            options={
                'verbose_name': '\u82f1\u6587TopDown\u65f6\u95f4\u4f9d\u8d56\u6027',
                'verbose_name_plural': '\u82f1\u6587TopDown\u65f6\u95f4\u4f9d\u8d56\u6027',
            },
        ),
        migrations.CreateModel(
            name='TDDesignCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587TopDown\u8bbe\u8ba1\u9636\u6bb5\u5c5e\u6027')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587TopDown\u8bbe\u8ba1\u9636\u6bb5',
                'verbose_name_plural': '\u4e2d\u6587TopDown\u8bbe\u8ba1\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='TDDesignDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedTopDown\u8bbe\u8ba1\u9636\u6bb5\u5c5e\u6027')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTopDown\u8bbe\u8ba1\u9636\u6bb5',
                'verbose_name_plural': '\u5fb7\u8bedTopDown\u8bbe\u8ba1\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='TDDesignEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_Name', models.CharField(default='', max_length=50, verbose_name='\u82f1\u6587TopDown\u8bbe\u8ba1\u9636\u6bb5\u5c5e\u6027')),
            ],
            options={
                'verbose_name': '\u82f1\u6587TopDown\u8bbe\u8ba1\u9636\u6bb5',
                'verbose_name_plural': '\u82f1\u6587TopDown\u8bbe\u8ba1\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='TDDurationCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587TopDown\u6301\u7eed\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587TopDown\u6301\u7eed\u65f6\u95f4',
                'verbose_name_plural': '\u4e2d\u6587TopDown\u6301\u7eed\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='TDDurationDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedTopDown\u6301\u7eed\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTopDown\u6301\u7eed\u65f6\u95f4',
                'verbose_name_plural': '\u5fb7\u8bedTopDown\u6301\u7eed\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='TDDurationEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587TopDown\u6301\u7eed\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u82f1\u6587TopDown\u6301\u7eed\u65f6\u95f4',
                'verbose_name_plural': '\u82f1\u6587TopDown\u6301\u7eed\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='TDEvaluationCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluation_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587TopDown\u8bc4\u4f30\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587TopDown\u8bc4\u4f30\u7c7b\u578b',
                'verbose_name_plural': '\u4e2d\u6587TopDown\u8bc4\u4f30\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='TDEvaluationDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluation_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedTopDown\u8bc4\u4f30\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTopDown\u8bc4\u4f30\u7c7b\u578b',
                'verbose_name_plural': '\u5fb7\u8bedTopDown\u8bc4\u4f30\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='TDEvaluationEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluation_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587TopDown\u8bc4\u4f30\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u82f1\u6587TopDown\u8bc4\u4f30\u7c7b\u578b',
                'verbose_name_plural': '\u82f1\u6587TopDown\u8bc4\u4f30\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='TDParticipationCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participation_Name', models.CharField(default='', max_length=20, verbose_name='\u4e2d\u6587TopDown\u7528\u6237\u53c2\u4e0e')),
            ],
            options={
                'verbose_name': '\u4e2d\u6587TopDown\u7528\u6237\u53c2\u4e0e',
                'verbose_name_plural': '\u4e2d\u6587TopDown\u7528\u6237\u53c2\u4e0e',
            },
        ),
        migrations.CreateModel(
            name='TDParticipationDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participation_Name', models.CharField(default='', max_length=20, verbose_name='\u5fb7\u8bedTopDown\u7528\u6237\u53c2\u4e0e')),
            ],
            options={
                'verbose_name': '\u5fb7\u8bedTopDown\u7528\u6237\u53c2\u4e0e',
                'verbose_name_plural': '\u5fb7\u8bedTopDown\u7528\u6237\u53c2\u4e0e',
            },
        ),
        migrations.CreateModel(
            name='TDParticipationEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participation_Name', models.CharField(default='', max_length=20, verbose_name='\u82f1\u6587TopDown\u7528\u6237\u53c2\u4e0e')),
            ],
            options={
                'verbose_name': '\u82f1\u6587TopDown\u7528\u6237\u53c2\u4e0e',
                'verbose_name_plural': '\u82f1\u6587TopDown\u7528\u6237\u53c2\u4e0e',
            },
        ),
    ]
